### ISSUE TITLE
Facing problem when the group slug name is same

### ISSUE THREAD

**Issue by MostafaRabia** [StydeNet/enlighten#21]
If there is two areas and one slug name for group, the data and route conflicts.
What is the solution?

**Comment by sileence** [comment]
Hi! @MostafaRabia could you please tell me an example of that? For example what test classes do you have?

I'll need to reproduce the error in local first before I try to solve the bug or approve your PR.

**Comment by MostafaRabia** [comment]
@sileence 
Hi!

I have 3 types of people: admin, teacher and user, and there is table for every one.
So i made it:
/tests/Admin/TableTest
/tests/Teacher/TableTest
/tests/User/TableTest
It's comfortable for me.

In enlighten this is the url:
enlighten/run/1/{area}/table
and examples searches on "table" and there is 3 with 3 areas not one area.
So in anything in admin, teacher and user there is one result, not 3 results for each area.
So i made this PR and worked for me, it's search on "table" and "area" togeather.

sorry for my bad english.

**Comment by MostafaRabia** [comment]
There is another problem about it, if the area is "feature" or "unit" and there is the same directions, will this problem be there too.

I prefer make it by "id" column not "slug".

**Comment by sileence** [comment]
@MostafaRabia thanks for reporting the issue! I found a way to get the example group without ambiguity while keeping the slugs! The change is in `main` for now (install with `dev-main`) and will release 0.2.10 in a few moments.

We want to continue using the slug because it's better if you re-run the tests, you can just refresh the page.

Sorry I don't understand the problem with the search? Do you mean the search bar?

**Comment by MostafaRabia** [comment]
No no i didn't mean the search bar.

Thank you.

**Comment by MostafaRabia** [comment]
@sileence 
Hi!

I tested it again today, in laravel the area is "feature" or "unit", how can i change it?
I tried add
`
<testsuite name="Feature/user">
            <directory suffix="Test.php">./tests/Feature/User</directory>
</testsuite>
`
in config/enlighten i tried many to add new area, it's shown in view but with no examples, what i tried:
`
'areas' => [
        'Feature/User'
    ],
//
'areas' => [
        'User'
    ],
//
'areas' => [
        'User' => 'Feature/User'
    ],
`
and nothing, the area is same in 'enlighten_example_groups' in DB.

so, what?

**Comment by sileence** [comment]
@MostafaRabia Each area represents a test suite. We call them "Areas" because a client or a QA person might not know what a test suite is.

By default each area is the second segment of your test class FQN in slug format, i.e.:

Tests\Feature\CreateUserTest -> feature
Tests\Unit\UserTest -> unit

---

Optional:

If you wish to customise the areas that are shown, you can add the areas key in your config, as an associative or simple array:

```
// config/enlighten.php

'areas' => ['feature', 'unit'],

// or:

'areas' => ['api' => 'API', 'feature' => 'Feature'],
```

Otherwise leave that config option commented.

That's just for display. That's not going to ignore tests. If you wish to ignore tests please read our readme file.

---

Optional:

You can also create your own custom area resolver if for any reason your areas / test suites are not the second segment of your test classes. This is an *advanced* option.

https://github.com/StydeNet/enlighten/blob/main/tests/Unit/EnlightenTest.php#L18

**Comment by MostafaRabia** [comment]
@sileence 
Thanks for your explaining.

Now in laravel, this command:
`
php artisan make:test ExampleTest
`
will make `ExampleTest` in `Feature` dir, and there is no way to make test inside any folders unless `Feature` and `Unit`.
So the problem is still exist. if anyone did `ExampleTest` in 2 sub dir in `Feature` folder, the area of them will "feature" and enlighten won't get exactly what programmer need, because the slug and area is same in all.

That just what i need to say.
in `TestExampleGroup` class in `getArea` function inside it, i changed index 1 to 2 and works prefectly.
And `Area` in models i did same and works prefectly too.

So how can user customize it to what he need?
I suggest the user can change index of `getArea` and `Area` class by config, and if there is no this index in test class name, will take the index - 1 or -2 and so on.

Thanks for your support.

**Comment by sileence** [comment]
@MostafaRabia You were right, from Enlighten 0.3.3 (just released) the example group slugs will include the sub-folders, preventing ambiguity. If that's not enough you can also add your own slug generator, have a look at:

https://github.com/StydeNet/enlighten/blob/main/tests/Unit/GeneratesSlugFromClassNameTest.php#L29

Thanks for reporting the issue :)

**Comment by MostafaRabia** [comment]
@sileence 
very thanks to you, now working like charm.
